//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crawler
    {
        public int ID { get; set; }
        public string Page_content { get; set; }
        public string Url { get; set; }
        public string Source_Url { get; set; }
    }
}
