//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inverted_index
    {
        public string Term { get; set; }
        public int Doc_ID { get; set; }
        public int Frequency { get; set; }
        public string Position { get; set; }
    }
}
