//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soundex_Index
    {
        public string term { get; set; }
        public string phonetic_hash { get; set; }
    }
}
